<a href="https://colab.research.google.com/github/sk-aili/Practice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Demonstration

In [1]:
# import numpy
import numpy as np

Initialize 1 dimensional numpy array

In [2]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
type(arr)

numpy.ndarray

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
# 1 dimensional array
arr.shape

(5,)

Create 2D numpy array

In [6]:
l1 = [1, 2, 3, 4, 5]
l2 = [1, 2, 3, 4, 5]
l3 = [1, 2, 3, 4, 5]

arr = np.array([l1, l2, l3])
arr.shape

(3, 5)

In [7]:
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])