<a href="https://colab.research.google.com/github/sk-aili/Practice/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas demonstration

Import pandas

In [1]:
import pandas as pd
import numpy as np

Create dataframe

In [2]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=['row1', 'row2', 'row3', 'row4', 'row5'], columns=['col1', 'col2', 'col3', 'col4'])

In [3]:
df.shape

(5, 4)

In [6]:
# top 5 rows data
df.head()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

save dataframe

In [ ]:
#df.to_csv('df.csv')

Locating elements
1. loc    
2. iloc

loc is used to locate/access elements using index name

In [8]:
# single index
df.loc['row1']

col1    0
col2    1
col3    2
col4    3
Name: row1, dtype: int64

In [10]:
# multiple indices
df.loc[['row1', 'row2']]

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7

Locate all rows from a column

In [15]:
df.loc[:, 'col1']

row1     0
row2     4
row3     8
row4    12
row5    16
Name: col1, dtype: int64

In [27]:
type(df.loc[:, 'col1'])

pandas.core.series.Series

In [28]:
type(df.loc[['row1', 'row2']])

pandas.core.frame.DataFrame

Multiple columns

In [16]:
df.loc[:, ['col1', 'col2']]

col1  col2
row1     0     1
row2     4     5
row3     8     9
row4    12    13
row5    16    17

iloc can be used to locate data using index number

In [17]:
# first row from all columns
df.iloc[0]

col1    0
col2    1
col3    2
col4    3
Name: row1, dtype: int64

In [18]:
# all rows from a column
df.iloc[:, 0]

row1     0
row2     4
row3     8
row4    12
row5    16
Name: col1, dtype: int64

In [23]:
# multiple rows from some columns
df.iloc[0:4, 1:3]

col2  col3
row1     1     2
row2     5     6
row3     9    10
row4    13    14

In [26]:
type(df.iloc[0])

pandas.core.series.Series

In [24]:
type(df.iloc[:, 0])

pandas.core.series.Series

In [25]:
type(df.iloc[0:4, 1:3])

pandas.core.frame.DataFrame

convert dataframe to array

In [32]:
df.iloc[:, :].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
df.iloc[1:, 1:].values

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [37]:
df.loc['row1':'row3'].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
df.loc[:, 'col1':'col2'].values

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

value counts

In [42]:
df['col1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: col1, dtype: int64

unique

In [43]:
df['col1'].unique()

array([ 0,  4,  8, 12, 16])

In [46]:
df[['col1', 'col2']]

col1  col2
row1     0     1
row2     4     5
row3     8     9
row4    12    13
row5    16    17